# server (eureka 默认端口为：8761)
server:
  port: 8761

# spring
spring:
  application:
    name: commonservice-erueka

# info自定义
#info: 
#  build: 
#    name: @project.name@
#    description: @project.description@
#    groupId: @project.groupId@
#    artifact: @project.artifactId@
#    version: @project.version@

# eureka
eureka: 
  client: 
    # 是否注册到eureka
    register-with-eureka: true
    # 是否从eureka获取注册信息
    fetch-registry: false
    availability-zones: 
      kosmos: kosmosZone
    service-url: 
      kosmosZone: http://kosmos:123456@localhost:8761/eureka/
      defaultZone: http://kosmos:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    metadataMap:
      zone: kosmosZone
      user: ${security.user.name}
      password: {security.user.password}
      
  # 指定环境
  environment: dev
  #指定数据中心
  datacenter: kosmos
  # 关闭自我保护模式
  server: 
    enable-self-preservation: false
  #设置清理无效节点的时间间隔，默认60000，即是60s
    eviction-interval-timer-in-ms: 60000

# 服务认证
security: 
  basic: 
    enabled: true
  user: 
    name: kosmos
    password: 123456

management:
  security:
    enabled: false